export const FRENCH_IBAN_ATTRIBUTES: {
  COUNTRY_CODE: string;
  COUNTRY_CODE_LENGTH: number;
  CHECK_DIGITS_LENGTH: number;
  BANK_CODE_LENGTH: number;
  BRANCH_CODE_LENGTH: number;
  ACCOUNT_NUMBER_LENGTH: number;
  RIB_KEY_LENGTH: number;
  TOTAL_IBAN_LENGTH: number;
  IBAN_PREFIX_LENGTH: number;
  BBAN_LENGTH: number;
} = {
  COUNTRY_CODE: 'FR',
  COUNTRY_CODE_LENGTH: 2,
  CHECK_DIGITS_LENGTH: 2,
  BANK_CODE_LENGTH: 5,
  BRANCH_CODE_LENGTH: 5,
  ACCOUNT_NUMBER_LENGTH: 11,
  RIB_KEY_LENGTH: 2,
  TOTAL_IBAN_LENGTH: 27,
  IBAN_PREFIX_LENGTH: 4,
  BBAN_LENGTH: 23,
};
